ulp-config: Add --cc, --ld arguments
Signed-off-by: Rong Tao <rongtao@cestc.cn>

diff --git a/src/ulp-config b/src/ulp-config
--- a/src/ulp-config
+++ b/src/ulp-config
@@ -8,6 +8,9 @@ readonly ANSI_GRAY="\033[2m"
 readonly ANSI_UNDERLINE="\033[4m"
 readonly ANSI_RESET="\033[m"
 
+CC=gcc
+LD=ld
+
 already_run=
 run_cflags=
 run_libs=
@@ -38,6 +41,12 @@ ${ANSI_BOLD}ARGUMENT${ANSI_RESET}
    --libs             Print all the libraries needed to link against the speci-
                       fied ULPatch components, including any dependencies.
 
+   --cc [COMPILER]    Specify compiler, default: ${CC}, you should specify this
+                      argument before --cflags.
+
+   --ld [LINKER]      Specify linker, default: ${LD}, you should specify this
+                      argument before --ldflags and --libs.
+
    -h, --help         show this help information
 
 ${ANSI_BOLD}SEE ALSO${ANSI_RESET}
@@ -55,6 +64,24 @@ goodbye()
 
 trap "goodbye" EXIT
 
+set_ld()
+{
+	LD=$1
+	${LD} --help 2>&1 >/dev/null || {
+		echo "ERROR: Bad ${LD}" >&2
+		exit 1
+	}
+}
+
+set_cc()
+{
+	CC=$1
+	${CC} --help 2>&1 >/dev/null || {
+		echo "ERROR: Bad ${CC}" >&2
+		exit 1
+	}
+}
+
 print_cflags()
 {
 	cflags+=( "-I/usr/include/" )
@@ -68,7 +95,7 @@ print_ldflags()
 	ldflags+=( "--build-id=sha1" )
 	ldflags+=( "-z noexecstack" )
 
-	if [[ "$(ld --help | grep no-warn-rwx-segments 2>/dev/null || true)" ]]; then
+	if [[ "$(${LD} --help | grep no-warn-rwx-segments 2>/dev/null || true)" ]]; then
 		ldflags+=( "--no-warn-rwx-segments" )
 	fi
 
@@ -82,6 +109,8 @@ print_libs()
 
 TEMP=$(getopt \
 	--options h \
+	--long cc: \
+	--long ld: \
 	--long cflags \
 	--long ldflags \
 	--long libs \
@@ -108,6 +137,16 @@ while true; do
 		shift
 		already_run=YES
 		run_libs=YES
+		;;
+	--cc)
+		shift
+		set_cc $1
+		shift
+		;;
+	--ld)
+		shift
+		set_ld $1
+		shift
 		;;
 	-h|--help)
 		shift
